# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
  pid_gains:
    HeadYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HeadPitch:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    WheelFL:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    WheelFR:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    WheelB:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RHand:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LHand:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LWristYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RWristYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    base_link_fixedjoint:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    base_footprint_joint:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HipRoll:
      p: 1000
      i: 0.1
      d: 5.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HipPitch:
      p: 1000
      i: 0.1
      d: 5.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LFinger11:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger12:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger13:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger11:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger12:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger13:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger21:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger22:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger23:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger21:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger22:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger23:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger31:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger32:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger33:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger31:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger32:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger33:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger41:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger42:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LFinger43:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger41:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger42:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RFinger43:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LThumb1:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RThumb1:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LThumb2:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    RThumb2:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    LElbowRoll:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RElbowRoll:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LElbowYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RElbowYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LShoulderRoll:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RShoulderRoll:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LShoulderPitch:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RShoulderPitch:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    KneePitch:
      p: 1000
      i: 0.1
      d: 5.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
